### ISSUE TITLE
Bug: wx.previewImage之后图片卡住了

### ISSUE THREAD

**Issue by codeshif** [jasondu/wxa-plugin-canvas#21]
Hello, @jasondu .

感谢您贡献开源项目，但是我发现了一个问题：
在**生成图片**并使用**wx.previewImage**预览，返回之后如图：

<img src="https://user-images.githubusercontent.com/35602158/46245810-a0c70900-c426-11e8-9ae0-76c630d72044.png" width="300" />

尝试解决办法去掉：
```css
.canvas.pro {
    /*去掉就没事了*/
    /*position: absolute;*/
    bottom: 0;
    left: 0;
    /*transform: translate3d(-999rpx, 0, 0);*/
}
```

难道是位置不对了吗，多谢
